#!/usr/bin/env bash
# install wpa supplicant config file created using the cat installers from cat.eduroam.org
# as described in the README
# Please don't use this if the PI will be running in an unsecured location, as the eduroam network account password/secret key will 
# be stored in plain text.
# Written by Jonatan Pipping <jpipping@kth.se>
# GPL V3
########
set -x
set -e

source /common.sh

echo "Running WPA_SUPPLICANT start chroot script"

unpack /filesystem/cat_installer /etc/wpa_supplicant/cat_installer root

if [ -f "/etc/wpa_supplicant/cat_installer/cat_installer.conf" ]
then
  sed -i 's#ca_cert=".*/ca.pem"#ca_cert="/etc/wpa_supplicant/cat_installer/ca.pem"#' '/etc/wpa_supplicant/cat_installer/cat_installer.conf'
  mv "/etc/wpa_supplicant/cat_installer/cat_installer.conf" "/etc/wpa_supplicant/wpa_supplicant.conf"
  cp "/etc/wpa_supplicant/wpa_supplicant.conf" "/boot/wpa_supplicant.conf"
fi

if [ ! -f "/etc/wpa_supplicant/cat_installer/ca.pem" ]
then
  rm -r "/etc/wpa_supplicant/cat_installer"
fi
