#!/usr/bin/env bash
# install wpa supplicant config file created using the cat installers from cat.eduroam.org
# as described in the README
# Please don't use this if the PI will be running in an unsecured location, as the eduroam network account password/secret key will 
# be stored in plain text.
# Written by Jonatan Pipping <jpipping@kth.se>
# GPL V3
########
set -x
set -e

source /common.sh

echo "Running WPA_SUPPLICANT start chroot script"

CAT_DIR=/var/wpa_supplicant_cat_installer

unpack "/filesystem/cat_installer" "$CAT_DIR" root

if [ -f "$CAT_DIR/cat_installer.conf" ]
then
  # set date to now
  unpack /filesystem/init /var/wpa_supplicant_init root
  date -s "$(cat /var/wpa_supplicant_init/date.txt)"
  rm -r /var/wpa_supplicant_init

  sed -i 's#ca_cert=".*/ca.pem"#ca_cert="/etc/wpa_supplicant/cat_installer/ca.pem"#' "$CAT_DIR/cat_installer.conf"
  echo "\
country=SE
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
" >> "$CAT_DIR/cat_installer.conf"

  cp "$CAT_DIR/cat_installer.conf" "/etc/wpa_supplicant/wpa_supplicant.conf"
  cp "$CAT_DIR/wpa_supplicant.conf" "/boot/wpa_supplicant.conf"
  cp "$CAT_DIR/wpa_supplicant.conf" "/boot/fullpageos-wpa-supplicant.txt"

  mkdir -p "/etc/wpa_supplicant/cat_installer"
  cp "$CAT_DIR/ca.pem" "/etc/wpa_supplicant/cat_installer/"

  rm -r "$CAT_DIR"
fi
